all:
  syMongodbOdmPlugin:
    databases:
      default:
        host: 127.0.0.1
        user: ''
        password: ''
        database: local
    types:
      date: symflo.mongodbodm.type.date
      string: symflo.mongodbodm.type.string
      integer: symflo.mongodbodm.type.integer
      pass: symflo.mongodbodm.type.pass
      manualReference: symflo.mongodbodm.type.manualreference
      manualReferences: symflo.mongodbodm.type.manualreferences
      embeddedCollection: symflo.mongodbodm.type.embeddedcollection
      embeddedOne: symflo.mongodbodm.type.embeddedone
